create table public.jobs_has_candidate_titles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  job_id bigint not null,
  candidate_title_id bigint not null,
  constraint jobs_has_candidate_titles_pkey primary key (id),
  constraint jobs_has_candidate_titles_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE,
  constraint jobs_has_candidate_titles_candidate_title_id_fkey foreign KEY (candidate_title_id) references candidate_titles (id) on delete CASCADE
) TABLESPACE pg_default;