create table public.organizations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  owner_id text not null default auth.jwt()->>'sub',
  name character varying not null,
  description text null,
  constraint organizations_pkey primary key (id)
) TABLESPACE pg_default;