create table public.job_process_steps (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  title character varying not null,
  description text null,
  sort_order smallint not null default '0'::smallint,
  job_id bigint not null,
  constraint job_process_steps_pkey primary key (id),
  constraint job_process_steps_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE
) TABLESPACE pg_default;