create table public.jobs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  status character varying not null,
  priority character varying not null,
  title character varying not null,
  description text null,
  headcount smallint not null default '0'::smallint,
  organization_id bigint not null,
  domain_id bigint not null,
  constraint jobs_pkey primary key (id),
  constraint jobs_organization_id_fkey foreign KEY (organization_id) references organizations (id) on delete CASCADE,
  constraint jobs_domain_id_fkey foreign KEY (domain_id) references job_domains (id) on delete CASCADE
) TABLESPACE pg_default;