create table public.organization_process_steps (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  title character varying not null,
  description text null,
  sort_order smallint not null default '0'::smallint,
  organization_id bigint not null,
  constraint organization_process_steps_pkey primary key (id),
  constraint organization_process_steps_organization_id_fkey foreign KEY (organization_id) references organizations (id) on delete CASCADE
) TABLESPACE pg_default;