create table public.job_domains (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  key character varying not null,
  name character varying not null,
  constraint job_domains_pkey primary key (id),
  constraint job_domains_key_key unique (key)
) TABLESPACE pg_default;