create table public.job_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  key character varying not null,
  title character varying not null,
  constraint job_types_pkey primary key (id)
) TABLESPACE pg_default;