create table public.candidate_processings (
  id bigint generated by default as identity not null,
  candidate_id bigint not null,
  job_process_step_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  status character varying not null,
  note text null,
  sort_order smallint not null default '0'::smallint,
  due_date timestamp with time zone not null default now(),
  constraint candidate_processings_pkey primary key (id),
  constraint candidate_processings_candidate_id_fkey foreign KEY (candidate_id) references candidates (id) on delete CASCADE,
  constraint candidate_processings_job_process_step_id_fkey foreign KEY (job_process_step_id) references job_process_steps (id) on delete CASCADE,
  constraint candidate_processings_job_process_step_id_candidate_id_uniq UNIQUE (candidate_id, job_process_step_id)
) TABLESPACE pg_default;