create table public.candidate_titles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  key character varying not null,
  title character varying not null,
  owner_id text not null default auth.jwt()->>'sub',
  constraint candidate_titles_pkey primary key (id)
) TABLESPACE pg_default;